In [1]:
import pandas as pd 
import numpy as np
import os 
import random
from nltk.tokenize import word_tokenize

In [2]:
default_path = os.getcwd()
data_path = os.path.join(default_path, 'data')

In [3]:
bws_dep = pd.read_csv(os.path.join(data_path, 'bws_dep_translated.csv'))
bws_ndep = pd.read_csv(os.path.join(data_path, 'bws_daily_translated.csv'))

In [4]:
bws_ndep

,text,translated
0,"If you look around Kiki, couples who fight are...",키키 주변을 둘러보면 싸우는 커플들이 화장을 잘한다. 키키.
1,"Yeah, we're still dating","그래, 우린 아직 사귀는 중이야"
2,"Since it's our 100th day, I don't think we nee...",저희가 100일이니까 너무 부담스럽게 할 필요는 없을 것 같아요
3,What do you think about giving me a card?,당신은 나에게 카드를 주는 것에 대해 어떻게 생각하나요?
4,It's already time to go...,벌써 갈 시간이 됐어요...
...,...,...
395,Or lie down on the electric pad,아니면 전기장판 위에 눕는다
396,Let's save money and go there,돈 모아서 거기 가자
397,"But if you need to go with me, you can decide....",하지만 나랑 같이 갈 일이 있으면 결정해도 돼...
398,It was really delicious.,꿀맛이었지요.
399,one's wife's family,처가

In [5]:
bws_dep

,text,translated
0,male aged i used to feel depressed since the ...,남자 나이 나는 '비정상적인' 의미에서 나이 이후로 우울함을 느끼곤 했다
1,i am not really sure why i am depressed i am n...,나는 내가 왜 우울한지 잘 모르겠다. 나는 결코 인기가 없지만 나는 친구들이 있다
2,i don't know if i can really give you any soli...,나 자신이 우울하기 때문에 내가 정말로 너에게 확실한 조언을 해줄 수 있을지 모르겠다
3,which is the same when i am depressed but at l...,그것은 내가 우울할 때도 마찬가지이지만 적어도 의학적 적응 전에 나는 잠시 동안 진...
4,i don't think i am depressed i just suck,나는 내가 우울하다고 생각하지 않아. 그냥 형편없어
...,...,...
1195,any nin while i am depressed not depressed hap...,내가 우울한 동안 아무 것도 우울하지 않고 행복하고 미친 것은 없다
1196,i like to be alone that's the only time when i...,나는 우울하지 않을 때 혼자 있는 것을 좋아한다
1197,when you don't feel depressed you feel a sick ...,당신이 우울하지 않을 때 당신은 그것에 대한 아픈 향수를 느낀다
1198,i am not depressed because i don't get out eno...,나는 충분히 밖으로 나가지 않기 때문에 우울하지 않다. 나는 우울하다. 그리고 그것...
1199,any relationships i create when i am not depre...,"내가 우울하지 않을 때 만드는 어떤 관계도 내가 다시 우울해 질 때 사라지는데, 이..."

In [6]:
bws_dep['len'] = bws_dep.text.str.len()
bws_dep.head(3)

,text,translated,len
0,male aged i used to feel depressed since the ...,남자 나이 나는 '비정상적인' 의미에서 나이 이후로 우울함을 느끼곤 했다,74
1,i am not really sure why i am depressed i am n...,나는 내가 왜 우울한지 잘 모르겠다. 나는 결코 인기가 없지만 나는 친구들이 있다,88
2,i don't know if i can really give you any soli...,나 자신이 우울하기 때문에 내가 정말로 너에게 확실한 조언을 해줄 수 있을지 모르겠다,79

In [7]:
bws_tok_len = [len(word_tokenize(text)) for text in bws_dep.text.values]

In [8]:
bws_dep['tok_len'] = bws_tok_len
bws_dep.head(3)

,text,translated,len,tok_len
0,male aged i used to feel depressed since the ...,남자 나이 나는 '비정상적인' 의미에서 나이 이후로 우울함을 느끼곤 했다,74,16
1,i am not really sure why i am depressed i am n...,나는 내가 왜 우울한지 잘 모르겠다. 나는 결코 인기가 없지만 나는 친구들이 있다,88,20
2,i don't know if i can really give you any soli...,나 자신이 우울하기 때문에 내가 정말로 너에게 확실한 조언을 해줄 수 있을지 모르겠다,79,18

In [9]:
bws_ndep

,text,translated
0,"If you look around Kiki, couples who fight are...",키키 주변을 둘러보면 싸우는 커플들이 화장을 잘한다. 키키.
1,"Yeah, we're still dating","그래, 우린 아직 사귀는 중이야"
2,"Since it's our 100th day, I don't think we nee...",저희가 100일이니까 너무 부담스럽게 할 필요는 없을 것 같아요
3,What do you think about giving me a card?,당신은 나에게 카드를 주는 것에 대해 어떻게 생각하나요?
4,It's already time to go...,벌써 갈 시간이 됐어요...
...,...,...
395,Or lie down on the electric pad,아니면 전기장판 위에 눕는다
396,Let's save money and go there,돈 모아서 거기 가자
397,"But if you need to go with me, you can decide....",하지만 나랑 같이 갈 일이 있으면 결정해도 돼...
398,It was really delicious.,꿀맛이었지요.
399,one's wife's family,처가

In [10]:
bws_dep.len.median()

79.0

In [11]:
bws_dep.tok_len.median()

16.0

In [12]:
print(f'텍스트 길이 중위 값: {bws_dep.len.median()}')
bws_short = bws_dep[bws_dep.len < 79]
bws_long = bws_dep[bws_dep.len >= 79]
print(f'bws_short 개수: {len(bws_short)}')
print(f'bws_long 개수: {len(bws_long)}')
bws_long.head(3)

텍스트 길이 중위 값: 79.0
bws_short 개수: 597
bws_long 개수: 603

,text,translated,len,tok_len
1,i am not really sure why i am depressed i am n...,나는 내가 왜 우울한지 잘 모르겠다. 나는 결코 인기가 없지만 나는 친구들이 있다,88,20
2,i don't know if i can really give you any soli...,나 자신이 우울하기 때문에 내가 정말로 너에게 확실한 조언을 해줄 수 있을지 모르겠다,79,18
3,which is the same when i am depressed but at l...,그것은 내가 우울할 때도 마찬가지이지만 적어도 의학적 적응 전에 나는 잠시 동안 진...,124,24

In [13]:
bws_long.sort_values('len')

,text,translated,len,tok_len
831,the only hard part is that i really don't want...,유일하게 어려운 부분은 내가 우울할 때 정말로 사회화하고 싶지 않다는 것이다,79,17
463,do i just ring up that place and tell them i a...,내가 그냥 그곳에 전화해서 내가 우울하다고 그들에게 말하는 것은 옳지 않은 것 같다,79,18
590,whether it's isolation drinking or cutting i n...,고립된 상태에서 술을 마시든 끊든 나는 우울할 때 무언가가 필요하다,79,14
560,i am depressed almost every day and last night...,나는 거의 매일 우울하고 어젯밤은 내가 지금까지 경험한 것 중 가장 최악의 밤이었다,79,17
1172,i don't feel depressed just sick and don't rea...,나는 단지 아프기만 한 우울증을 느끼지 않고 진정으로 항우울제를 복용하고 싶지도 않다,79,16
...,...,...,...,...
451,that might help those in depression or others ...,그것은 우울증에 있는 사람들이나 다른 사람들이 우울증을 더 잘 이해하는 데 도움이 ...,164,27
966,i've tried coming up with reasons why i should...,나는 우울한 에피소드를 촉발할 수 있었던 내 과거의 사건들을 본질적으로 우울하게 느...,164,30
792,slowly i started to realize that my unconsciou...,천천히 나는 내 무의식이 삶의 사건들과 그 사건들에 대한 나의 의식적인 보통 부정적...,166,27
13,most people would probably feel depressed with...,대부분의 사람들은 아마도 당신이 겪고 있는 스트레스로 우울함을 느낄 것이다. 그것은...,167,31
1199,any relationships i create when i am not depre...,"내가 우울하지 않을 때 만드는 어떤 관계도 내가 다시 우울해 질 때 사라지는데, 이...",174,30

In [14]:
## 831 463 590
bws_long.drop(831, inplace=True)
bws_long.drop(463, inplace=True)
bws_long.drop(590, inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [15]:
bws_short.loc[831] = bws_dep.loc[831]
bws_short.loc[463] = bws_dep.loc[463]
bws_short.loc[590] = bws_dep.loc[590]

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:692: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

In [19]:
len(bws_short), len(bws_long)

(600, 600)

In [20]:
bws_set = []

bws_set1 = dict()
bws_set2 = dict()
bws_set3 = dict()
bws_set4 = dict()
bws_set5 = dict()
bws_set6 = dict()
bws_set7 = dict()
bws_set8 = dict()

bws_set = [bws_set1, bws_set2, bws_set3, bws_set4, bws_set5, bws_set6, bws_set7, bws_set8]
bws_set

[{}, {}, {}, {}, {}, {}, {}, {}]

In [21]:
bws_set[0]

{}

In [27]:
def check_common_tok(idx_list, thresh):
    tok_list = []
    for idx in idx_list:
        try:
            tok_list.append(set(word_tokenize(bws_dep.loc[idx].text)))
        except:
            print(idx)
            continue
    
    for idx in range(3):  # 0,1 
        for idx2 in range(1+idx, 3):   # 0: 1, 2, 1: 2
            if len(tok_list[idx] & tok_list[idx2]) >= thresh:   # 교집합 
                # print(f'{idx_list[idx]}, {idx_list[idx2]}간에 공통 토큰이 {thresh}개 이상입니다.')
                # print(tok_list[idx] & tok_list[idx2])
                return False 
    return True

In [23]:
def is_duplicated(prev_idx_list, idx_list):
    if idx_list in prev_idx_list:
        print(f'중복 질문지입니다.')
        return True
    else:
        return False

In [24]:
bws_short.sort_values('text')

,text,translated,len,tok_len
482,and i am depressed,그리고 나는 우울하다,19,4
327,and i think i am depressed,그리고 나는 우울하다고 생각한다,27,6
1156,but i don't feel depressed,하지만 나는 우울하지 않다,27,6
1074,but i don't feel depressed anymore,하지만 나는 더 이상 우울하지 않아,35,7
751,i am depressed because of x,나는 x 때문에 우울하다,28,6
...,...,...,...,...
5,you may want to phrase it like i feel like i a...,당신은 내가 우울해 하는 것처럼 표현하고 싶을지도 모른다,57,13
1035,you never know if you are truly don't feel dep...,너는 네가 정말 우울하지 않은지 절대 모른다,52,11
40,you say hi i think i am depressed and i would ...,당신은 안녕이라고 말합니다. 나는 우울하고 도움이 필요합니다,60,14
356,you're lucky i am depressed right now and have...,내가 지금 우울하고 마실 것이 없어서 너는 운이 좋다,63,13
1152,you're not thinking about it so you don't feel...,당신은 우울해하지 않기 위해 그것에 대해 생각하고 있지 않다,56,12

In [25]:
len(bws_short) // 3 + 1, 200 + len(bws_long) // 3 + 1

(201, 401)

In [28]:
short_idx = bws_short.index.tolist()
long_idx = bws_long.index.tolist()
for idx in range(1, len(bws_short) // 3 + 1):
    cnt = 0 
    idx_list = random.sample(short_idx, 3)
    while check_common_tok(idx_list, 5) == False:
        cnt += 1 
        # print(idx_list)
        idx_list = random.sample(short_idx, 3)
        if cnt == len(short_idx):
            break 
    bws_set[0]['Q' + str(idx)] = idx_list
    for idx2 in idx_list:
        short_idx.remove(idx2)

print(idx)
for idx in range(201, 200 + len(bws_long) // 3 + 1):
    cnt = 0
    idx_list = random.sample(long_idx, 3)
    while check_common_tok(idx_list, 8) == False:
        cnt += 1 
        idx_list = random.sample(long_idx, 3)
        if cnt == len(long_idx):
            break 
    bws_set[0]['Q' + str(idx)] = idx_list
    for idx2 in idx_list:
        long_idx.remove(idx2)

print(idx)

200
400

In [29]:
bws_set[0]

{'Q1': [322, 716, 598],
 'Q2': [584, 913, 715],
 'Q3': [293, 775, 127],
 'Q4': [529, 528, 165],
 'Q5': [740, 925, 1016],
 'Q6': [503, 940, 1105],
 'Q7': [0, 653, 109],
 'Q8': [1035, 668, 634],
 'Q9': [11, 607, 1071],
 'Q10': [714, 593, 905],
 'Q11': [620, 681, 1120],
 'Q12': [692, 294, 396],
 'Q13': [132, 1129, 820],
 'Q14': [910, 672, 381],
 'Q15': [113, 937, 98],
 'Q16': [1168, 140, 729],
 'Q17': [721, 941, 734],
 'Q18': [892, 964, 850],
 'Q19': [1089, 539, 469],
 'Q20': [432, 63, 407],
 'Q21': [532, 709, 522],
 'Q22': [1075, 97, 673],
 'Q23': [626, 967, 348],
 'Q24': [525, 1156, 974],
 'Q25': [719, 296, 662],
 'Q26': [700, 534, 346],
 'Q27': [94, 255, 1180],
 'Q28': [713, 766, 641],
 'Q29': [369, 433, 305],
 'Q30': [217, 704, 575],
 'Q31': [1162, 541, 349],
 'Q32': [757, 284, 680],
 'Q33': [311, 505, 679],
 'Q34': [259, 497, 655],
 'Q35': [40, 1155, 659],
 'Q36': [14, 882, 629],
 'Q37': [486, 895, 995],
 'Q38': [608, 89, 1027],
 'Q39': [1021, 580, 53],
 'Q40': [698, 880, 854],
 'Q41': [398, 909, 133],
 'Q42': [194, 571, 569],
 'Q43': [298, 379, 693],
 'Q44': [963, 770, 27],
 'Q45': [394, 448, 1014],
 'Q46': [899, 1078, 743],
 'Q47': [154, 582, 472],
 'Q48': [788, 16, 238],
 'Q49': [149, 1140, 450],
 'Q50': [290, 535, 331],
 'Q51': [862, 1026, 879],
 'Q52': [466, 54, 762],
 'Q53': [427, 1174, 993],
 'Q54': [75, 636, 328],
 'Q55': [356, 996, 110],
 'Q56': [1189, 195, 153],
 'Q57': [836, 69, 142],
 'Q58': [1081, 823, 179],
 'Q59': [847, 918, 206],
 'Q60': [126, 851, 287],
 'Q61': [5, 1190, 833],
 'Q62': [452, 546, 66],
 'Q63': [358, 128, 137],
 'Q64': [122, 1086, 647],
 'Q65': [645, 695, 691],
 'Q66': [588, 333, 901],
 'Q67': [914, 745, 870],
 'Q68': [947, 688, 489],
 'Q69': [764, 1093, 490],
 'Q70': [1050, 354, 282],
 'Q71': [951, 760, 990],
 'Q72': [464, 1152, 1085],
 'Q73': [23, 506, 843],
 'Q74': [1034, 758, 973],
 'Q75': [1125, 88, 845],
 'Q76': [991, 248, 189],
 'Q77': [727, 17, 1039],
 'Q78': [710, 197, 988],
 'Q79': [202, 487, 323],
 'Q80': [25, 594, 1101],
 'Q81': [975, 33, 776],
 'Q82': [36, 1049, 147],
 'Q83': [200, 438, 1123],
 'Q84': [77, 530, 4],
 'Q85': [456, 1142, 860],
 'Q86': [524, 1111, 362],
 'Q87': [375, 958, 431],
 'Q88': [239, 829, 790],
 'Q89': [283, 922, 1077],
 'Q90': [831, 1143, 1060],
 'Q91': [514, 1146, 409],
 'Q92': [236, 478, 944],
 'Q93': [822, 424, 198],
 'Q94': [271, 138, 300],
 'Q95': [1048, 968, 965],
 'Q96': [927, 87, 725],
 'Q97': [429, 1118, 1166],
 'Q98': [1197, 599, 619],
 'Q99': [62, 406, 405],
 'Q100': [1030, 954, 888],
 'Q101': [166, 359, 270],
 'Q102': [214, 436, 415],
 'Q103': [834, 1005, 6],
 'Q104': [493, 237, 981],
 'Q105': [351, 15, 797],
 'Q106': [229, 810, 440],
 'Q107': [281, 167, 1025],
 'Q108': [171, 924, 657],
 'Q109': [257, 144, 1022],
 'Q110': [526, 950, 835],
 'Q111': [971, 159, 413],
 'Q112': [1043, 881, 38],
 'Q113': [428, 461, 79],
 'Q114': [842, 752, 1195],
 'Q115': [1080, 361, 566],
 'Q116': [204, 335, 596],
 'Q117': [825, 502, 774],
 'Q118': [827, 340, 630],
 'Q119': [225, 676, 853],
 'Q120': [108, 273, 613],
 'Q121': [31, 816, 1059],
 'Q122': [193, 201, 726],
 'Q123': [9, 555, 221],
 'Q124': [601, 482, 684],
 'Q125': [387, 365, 1147],
 'Q126': [378, 804, 44],
 'Q127': [390, 1020, 938],
 'Q128': [531, 998, 885],
 'Q129': [299, 1038, 8],
 'Q130': [42, 1163, 586],
 'Q131': [875, 146, 442],
 'Q132': [218, 671, 355],
 'Q133': [815, 10, 1177],
 'Q134': [56, 771, 631],
 'Q135': [367, 269, 840],
 'Q136': [654, 107, 96],
 'Q137': [152, 21, 632],
 'Q138': [543, 1063, 873],
 'Q139': [474, 251, 344],
 'Q140': [661, 891, 455],
 'Q141': [470, 978, 742],
 'Q142': [178, 777, 462],
 'Q143': [112, 85, 625],
 'Q144': [1116, 894, 411],
 'Q145': [604, 402, 319],
 'Q146': [227, 660, 12],
 'Q147': [1138, 877, 579],
 'Q148': [948, 511, 811],
 'Q149': [28, 992, 316],
 'Q150': [623, 211, 463],
 'Q151': [666, 441, 395],
 'Q152': [148, 670, 352],
 'Q153': [824, 408, 280],
 'Q154': [454, 590, 622],
 'Q155': [1161, 327, 250],
 'Q156': [1037, 756, 52],
 'Q157': [1097, 219, 501],
 'Q158': [1023, 664, 689],
 'Q159': [1193, 837, 86],
 'Q160': [101, 908, 934],
 'Q161': [263, 1122, 849],
 'Q162': [277, 956, 275],
 'Q163': [1117, 176, 1054],
 'Q164': [1090, 372, 557],
 'Q165': [499, 863, 928],
 'Q166': [1178, 906, 134],
 'Q167': [1069, 893, 737],
 'Q168': [806, 208, 302],
 'Q169': [1194, 435, 640],
 'Q170': [1041, 121, 562],
 'Q171': [256, 353, 561],
 'Q172': [184, 1099, 314],
 'Q173': [649, 190, 597],
 'Q174': [1151, 859, 583],
 'Q175': [1028, 181, 751],
 'Q176': [364, 977, 955],
 'Q177': [556, 857, 458],
 'Q178': [118, 808, 182],
 'Q179': [852, 639, 694],
 'Q180': [403, 232, 855],
 'Q181': [931, 449, 628],
 'Q182': [1102, 99, 568],
 'Q183': [1130, 809, 904],
 'Q184': [796, 841, 192],
 'Q185': [802, 912, 377],
 'Q186': [1165, 49, 252],
 'Q187': [1065, 935, 917],
 'Q188': [57, 1121, 718],
 'Q189': [1024, 552, 587],
 'Q190': [994, 976, 945],
 'Q191': [1047, 515, 1185],
 'Q192': [669, 1092, 960],
 'Q193': [1000, 1173, 266],
 'Q194': [1074, 92, 761],
 'Q195': [1009, 425, 168],
 'Q196': [1169, 199, 1107],
 'Q197': [1073, 1175, 185],
 'Q198': [772, 205, 326],
 'Q199': [116, 484, 1148],
 'Q200': [890, 1196, 1160],
 'Q201': [1003, 72, 933],
 'Q202': [1132, 74, 633],
 'Q203': [949, 739, 920],
 'Q204': [682, 292, 131],
 'Q205': [174, 652, 130],
 'Q206': [1136, 114, 678],
 'Q207': [313, 104, 82],
 'Q208': [446, 1068, 1128],
 'Q209': [615, 730, 414],
 'Q210': [301, 397, 295],
 'Q211': [703, 141, 1110],
 'Q212': [861, 318, 866],
 'Q213': [399, 550, 612],
 'Q214': [1096, 172, 1052],
 'Q215': [886, 605, 371],
 'Q216': [212, 921, 494],
 'Q217': [71, 1154, 738],
 'Q218': [129, 510, 170],
 'Q219': [1179, 213, 791],
 'Q220': [215, 500, 1011],
 'Q221': [317, 1113, 123],
 'Q222': [868, 1145, 919],
 'Q223': [286, 376, 602],
 'Q224': [177, 759, 125],
 'Q225': [983, 196, 753],
 'Q226': [533, 2, 1108],
 'Q227': [481, 903, 13],
 'Q228': [563, 124, 151],
 'Q229': [987, 135, 264],
 'Q230': [1115, 577, 1066],
 'Q231': [542, 233, 621],
 'Q232': [240, 389, 265],
 'Q233': [830, 807, 769],
 'Q234': [551, 29, 915],
 'Q235': [871, 702, 460],
 'Q236': [642, 246, 1091],
 'Q237': [1100, 1033, 1186],
 'Q238': [907, 656, 650],
 'Q239': [897, 980, 724],
 'Q240': [247, 943, 839],
 'Q241': [1137, 643, 476],
 'Q242': [554, 437, 573],
 'Q243': [261, 341, 274],
 'Q244': [565, 560, 646],
 'Q245': [773, 1036, 984],
 'Q246': [285, 953, 260],
 'Q247': [504, 288, 26],
 'Q248': [91, 997, 400],
 'Q249': [794, 320, 268],
 'Q250': [418, 60, 447],
 'Q251': [1017, 637, 186],
 'Q252': [422, 1150, 374],
 'Q253': [1082, 19, 1045],
 'Q254': [658, 723, 479],
 'Q255': [457, 312, 867],
 'Q256': [663, 451, 986],
 'Q257': [473, 821, 388],
 'Q258': [488, 581, 1191],
 'Q259': [957, 1149, 779],
 'Q260': [419, 518, 520],
 'Q261': [614, 262, 373],
 'Q262': [603, 1067, 749],
 'Q263': [1008, 959, 34],
 'Q264': [391, 203, 896],
 'Q265': [444, 1159, 1198],
 'Q266': [1171, 989, 512],
 'Q267': [708, 1094, 509],
 'Q268': [420, 453, 798],
 'Q269': [585, 932, 157],
 'Q270': [1002, 338, 3],
 'Q271': [786, 1053, 792],
 'Q272': [574, 216, 1164],
 'Q273': [1012, 115, 1056],
 'Q274': [812, 307, 64],
 'Q275': [717, 750, 480],
 'Q276': [1061, 1199, 675],
 'Q277': [527, 1031, 90],
 'Q278': [249, 572, 576],
 'Q279': [780, 979, 315],
 'Q280': [887, 844, 869],
 'Q281': [1124, 102, 1084],
 'Q282': [145, 1114, 1072],
 'Q283': [235, 874, 838],
 'Q284': [47, 163, 136],
 'Q285': [243, 697, 465],
 'Q286': [648, 513, 439],
 'Q287': [781, 161, 445],
 'Q288': [111, 611, 162],
 'Q289': [876, 705, 667],
 'Q290': [800, 916, 961],
 'Q291': [342, 383, 430],
 'Q292': [357, 1015, 706],
 'Q293': [936, 41, 733],
 'Q294': [884, 1133, 37],
 'Q295': [558, 7, 477],
 'Q296': [18, 306, 475],
 'Q297': [226, 570, 207],
 'Q298': [393, 421, 544],
 'Q299': [68, 538, 1176],
 'Q300': [48, 244, 61],
 'Q301': [95, 150, 889],
 'Q302': [1, 1134, 767],
 'Q303': [360, 81, 1019],
 'Q304': [699, 1029, 1004],
 'Q305': [1087, 272, 728],
 'Q306': [929, 471, 828],
 'Q307': [459, 345, 20],
 'Q308': [423, 209, 191],
 'Q309': [507, 1135, 106],
 'Q310': [707, 289, 70],
 'Q311': [254, 685, 380],
 'Q312': [485, 674, 736],
 'Q313': [883, 799, 1188],
 'Q314': [696, 644, 690],
 'Q315': [291, 627, 982],
 'Q316': [741, 523, 1088],
 'Q317': [1182, 1127, 143],
 'Q318': [158, 1192, 537],
 'Q319': [310, 865, 942],
 'Q320': [386, 1141, 686],
 'Q321': [1103, 814, 46],
 'Q322': [536, 187, 180],
 'Q323': [93, 347, 321],
 'Q324': [308, 384, 952],
 'Q325': [278, 795, 67],
 'Q326': [1001, 1046, 858],
 'Q327': [43, 100, 336],
 'Q328': [711, 902, 898],
 'Q329': [687, 517, 540],
 'Q330': [1170, 253, 638],
 'Q331': [363, 117, 30],
 'Q332': [385, 1183, 32],
 'Q333': [39, 339, 303],
 'Q334': [164, 1144, 818],
 'Q335': [651, 744, 606],
 'Q336': [985, 578, 1098],
 'Q337': [1095, 832, 801],
 'Q338': [401, 665, 1139],
 'Q339': [803, 1106, 496],
 'Q340': [1062, 701, 426],
 'Q341': [778, 1104, 309],
 'Q342': [55, 508, 242],
 'Q343': [169, 846, 683],
 'Q344': [962, 412, 624],
 'Q345': [826, 793, 516],
 'Q346': [600, 139, 119],
 'Q347': [926, 878, 1126],
 'Q348': [618, 564, 1007],
 'Q349': [616, 83, 468],
 'Q350': [1184, 864, 1013],
 'Q351': [1119, 1055, 966],
 'Q352': [722, 969, 1157],
 'Q353': [1167, 297, 813],
 'Q354': [160, 946, 80],
 'Q355': [155, 337, 1064],
 'Q356': [24, 589, 521],
 'Q357': [784, 1181, 45],
 'Q358': [434, 220, 746],
 'Q359': [324, 548, 329],
 'Q360': [404, 498, 59],
 'Q361': [224, 1040, 78],
 'Q362': [712, 1172, 417],
 'Q363': [819, 765, 156],
 'Q364': [228, 188, 334],
 'Q365': [559, 677, 330],
 'Q366': [241, 234, 1187],
 'Q367': [972, 1006, 720],
 'Q368': [547, 51, 748],
 'Q369': [591, 1010, 73],
 'Q370': [175, 443, 1070],
 'Q371': [999, 105, 332],
 'Q372': [392, 782, 120],
 'Q373': [789, 76, 343],
 'Q374': [635, 416, 1018],
 'Q375': [617, 410, 279],
 'Q376': [368, 930, 567],
 'Q377': [382, 50, 848],
 'Q378': [1032, 595, 610],
 'Q379': [210, 787, 276],
 'Q380': [1131, 35, 1083],
 'Q381': [258, 1044, 747],
 'Q382': [223, 805, 592],
 'Q383': [1058, 491, 366],
 'Q384': [768, 856, 245],
 'Q385': [1076, 467, 549],
 'Q386': [911, 222, 754],
 'Q387': [370, 22, 1051],
 'Q388': [763, 304, 65],
 'Q389': [923, 732, 230],
 'Q390': [350, 783, 872],
 'Q391': [519, 1079, 267],
 'Q392': [939, 103, 231],
 'Q393': [553, 173, 755],
 'Q394': [545, 735, 183],
 'Q395': [1153, 1112, 609],
 'Q396': [731, 817, 1158],
 'Q397': [1109, 325, 84],
 'Q398': [1042, 1057, 492],
 'Q399': [970, 58, 495],
 'Q400': [900, 483, 785]}

In [30]:
prev_idx_list = list(bws_set[0].values())

In [31]:
for idx in range(1, 8):
    short_idx = bws_short.index.tolist()
    long_idx = bws_long.index.tolist()
    for idx2 in range(1, len(bws_short) // 3 + 1):
        cnt = 0 
        idx_list = random.sample(short_idx, 3)
        while check_common_tok(idx_list, 5) == False or is_duplicated(prev_idx_list, idx_list) == True:
            cnt += 1 
            idx_list = random.sample(short_idx, 3)
            if cnt == len(short_idx):
                break 
        bws_set[idx]['Q' + str(idx2)] = idx_list
        for idx3 in idx_list:
            short_idx.remove(idx3)

    print(idx2)
    for idx2 in range(201, 200 + len(bws_long) // 3 + 1):
        cnt = 0
        idx_list2 = random.sample(long_idx, 3)
        while check_common_tok(idx_list2, 8) == False or is_duplicated(prev_idx_list, idx_list2) == True:
            cnt += 1 
            idx_list2 = random.sample(long_idx, 3)
            if cnt == len(long_idx):
                break 
        bws_set[idx]['Q' + str(idx2)] = idx_list2
        for idx3 in idx_list2:
            long_idx.remove(idx3)
            
    prev_idx_list.extend(list(bws_set[idx-1].values()))
    print(idx2)

200
400
200
400
200
400
200
400
200
400
200
400
200
400

In [32]:
bws_ndep

,text,translated
0,"If you look around Kiki, couples who fight are...",키키 주변을 둘러보면 싸우는 커플들이 화장을 잘한다. 키키.
1,"Yeah, we're still dating","그래, 우린 아직 사귀는 중이야"
2,"Since it's our 100th day, I don't think we nee...",저희가 100일이니까 너무 부담스럽게 할 필요는 없을 것 같아요
3,What do you think about giving me a card?,당신은 나에게 카드를 주는 것에 대해 어떻게 생각하나요?
4,It's already time to go...,벌써 갈 시간이 됐어요...
...,...,...
395,Or lie down on the electric pad,아니면 전기장판 위에 눕는다
396,Let's save money and go there,돈 모아서 거기 가자
397,"But if you need to go with me, you can decide....",하지만 나랑 같이 갈 일이 있으면 결정해도 돼...
398,It was really delicious.,꿀맛이었지요.
399,one's wife's family,처가

In [33]:
bws_ndep.index += 1200
bws_ndep

,text,translated
1200,"If you look around Kiki, couples who fight are...",키키 주변을 둘러보면 싸우는 커플들이 화장을 잘한다. 키키.
1201,"Yeah, we're still dating","그래, 우린 아직 사귀는 중이야"
1202,"Since it's our 100th day, I don't think we nee...",저희가 100일이니까 너무 부담스럽게 할 필요는 없을 것 같아요
1203,What do you think about giving me a card?,당신은 나에게 카드를 주는 것에 대해 어떻게 생각하나요?
1204,It's already time to go...,벌써 갈 시간이 됐어요...
...,...,...
1595,Or lie down on the electric pad,아니면 전기장판 위에 눕는다
1596,Let's save money and go there,돈 모아서 거기 가자
1597,"But if you need to go with me, you can decide....",하지만 나랑 같이 갈 일이 있으면 결정해도 돼...
1598,It was really delicious.,꿀맛이었지요.
1599,one's wife's family,처가

In [34]:
ndep_idx = bws_ndep.index.tolist()
random.sample(ndep_idx, 1)[0]

1439

In [35]:
bws_dep

,text,translated,len,tok_len
0,male aged i used to feel depressed since the ...,남자 나이 나는 '비정상적인' 의미에서 나이 이후로 우울함을 느끼곤 했다,74,16
1,i am not really sure why i am depressed i am n...,나는 내가 왜 우울한지 잘 모르겠다. 나는 결코 인기가 없지만 나는 친구들이 있다,88,20
2,i don't know if i can really give you any soli...,나 자신이 우울하기 때문에 내가 정말로 너에게 확실한 조언을 해줄 수 있을지 모르겠다,79,18
3,which is the same when i am depressed but at l...,그것은 내가 우울할 때도 마찬가지이지만 적어도 의학적 적응 전에 나는 잠시 동안 진...,124,24
4,i don't think i am depressed i just suck,나는 내가 우울하다고 생각하지 않아. 그냥 형편없어,40,10
...,...,...,...,...
1195,any nin while i am depressed not depressed hap...,내가 우울한 동안 아무 것도 우울하지 않고 행복하고 미친 것은 없다,61,11
1196,i like to be alone that's the only time when i...,나는 우울하지 않을 때 혼자 있는 것을 좋아한다,67,16
1197,when you don't feel depressed you feel a sick ...,당신이 우울하지 않을 때 당신은 그것에 대한 아픈 향수를 느낀다,62,13
1198,i am not depressed because i don't get out eno...,나는 충분히 밖으로 나가지 않기 때문에 우울하지 않다. 나는 우울하다. 그리고 그것...,99,23
1199,any relationships i create when i am not depre...,"내가 우울하지 않을 때 만드는 어떤 관계도 내가 다시 우울해 질 때 사라지는데, 이...",174,30

In [36]:
for idx in range(len(bws_set)):
    ndep_idx = bws_ndep.index.tolist()
    for q_list in bws_set[idx].values():
        nidx = random.sample(ndep_idx, 1)
        q_list.append(nidx[0])
        ndep_idx.remove(nidx[0])

In [38]:
import pickle 

with open(os.path.join(data_path, 'bws_set.pickle'), 'wb') as f:
    pickle.dump(bws_set, f, pickle.HIGHEST_PROTOCOL)

In [39]:
for num in range(0, 8):
    idx_list = []
    for idx_set in list(bws_set[num].values()):
        for idx in idx_set:
            idx_list.append(idx)
    
    print(f'Set{num} 중복 데이터 검사: {len(set(idx_list))}')

Set0 중복 데이터 검사: 1600
Set1 중복 데이터 검사: 1600
Set2 중복 데이터 검사: 1600
Set3 중복 데이터 검사: 1600
Set4 중복 데이터 검사: 1600
Set5 중복 데이터 검사: 1600
Set6 중복 데이터 검사: 1600
Set7 중복 데이터 검사: 1600